[local]
localhost

[mongodb]
mongodb.nirfaws.online

[redis]
redis.nirfaws.online

[mysql]
mysql.nirfaws.online

[rabbitmq]
rabbitmq.nirfaws.online

[catalogue]
catalouge.nirfaws.online

[user]
user.nirfaws.online

[cart]
cart.nirfaws.online

[shipping]
shipping.nirfaws.online

[payment]
payment.nirfaws.online

[frontend]
frontend.nirfaws.online